// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: agent/v1/agent.proto

package agentv1

import (
	v1 "github.com/observabil/arcade/api/task/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent状态枚举
type AgentStatus int32

const (
	AgentStatus_AGENT_STATUS_UNSPECIFIED AgentStatus = 0
	AgentStatus_AGENT_STATUS_ONLINE      AgentStatus = 1 // 在线
	AgentStatus_AGENT_STATUS_OFFLINE     AgentStatus = 2 // 离线
	AgentStatus_AGENT_STATUS_BUSY        AgentStatus = 3 // 忙碌
	AgentStatus_AGENT_STATUS_IDLE        AgentStatus = 4 // 空闲
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNSPECIFIED",
		1: "AGENT_STATUS_ONLINE",
		2: "AGENT_STATUS_OFFLINE",
		3: "AGENT_STATUS_BUSY",
		4: "AGENT_STATUS_IDLE",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNSPECIFIED": 0,
		"AGENT_STATUS_ONLINE":      1,
		"AGENT_STATUS_OFFLINE":     2,
		"AGENT_STATUS_BUSY":        3,
		"AGENT_STATUS_IDLE":        4,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_agent_v1_agent_proto_enumTypes[0]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

// 标签操作符
type LabelOperator int32

const (
	LabelOperator_LABEL_OPERATOR_UNSPECIFIED LabelOperator = 0
	LabelOperator_LABEL_OPERATOR_IN          LabelOperator = 1 // 标签值在values列表中
	LabelOperator_LABEL_OPERATOR_NOT_IN      LabelOperator = 2 // 标签值不在values列表中
	LabelOperator_LABEL_OPERATOR_EXISTS      LabelOperator = 3 // 标签key存在
	LabelOperator_LABEL_OPERATOR_NOT_EXISTS  LabelOperator = 4 // 标签key不存在
	LabelOperator_LABEL_OPERATOR_GT          LabelOperator = 5 // 标签值大于指定值（用于数值比较）
	LabelOperator_LABEL_OPERATOR_LT          LabelOperator = 6 // 标签值小于指定值（用于数值比较）
)

// Enum value maps for LabelOperator.
var (
	LabelOperator_name = map[int32]string{
		0: "LABEL_OPERATOR_UNSPECIFIED",
		1: "LABEL_OPERATOR_IN",
		2: "LABEL_OPERATOR_NOT_IN",
		3: "LABEL_OPERATOR_EXISTS",
		4: "LABEL_OPERATOR_NOT_EXISTS",
		5: "LABEL_OPERATOR_GT",
		6: "LABEL_OPERATOR_LT",
	}
	LabelOperator_value = map[string]int32{
		"LABEL_OPERATOR_UNSPECIFIED": 0,
		"LABEL_OPERATOR_IN":          1,
		"LABEL_OPERATOR_NOT_IN":      2,
		"LABEL_OPERATOR_EXISTS":      3,
		"LABEL_OPERATOR_NOT_EXISTS":  4,
		"LABEL_OPERATOR_GT":          5,
		"LABEL_OPERATOR_LT":          6,
	}
)

func (x LabelOperator) Enum() *LabelOperator {
	p := new(LabelOperator)
	*p = x
	return p
}

func (x LabelOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LabelOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_agent_proto_enumTypes[1].Descriptor()
}

func (LabelOperator) Type() protoreflect.EnumType {
	return &file_agent_v1_agent_proto_enumTypes[1]
}

func (x LabelOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LabelOperator.Descriptor instead.
func (LabelOperator) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

// 插件位置
type PluginLocation int32

const (
	PluginLocation_PLUGIN_LOCATION_UNSPECIFIED PluginLocation = 0
	PluginLocation_PLUGIN_LOCATION_SERVER      PluginLocation = 1 // 服务端文件系统
	PluginLocation_PLUGIN_LOCATION_STORAGE     PluginLocation = 2 // 对象存储
	PluginLocation_PLUGIN_LOCATION_REGISTRY    PluginLocation = 3 // 插件仓库
)

// Enum value maps for PluginLocation.
var (
	PluginLocation_name = map[int32]string{
		0: "PLUGIN_LOCATION_UNSPECIFIED",
		1: "PLUGIN_LOCATION_SERVER",
		2: "PLUGIN_LOCATION_STORAGE",
		3: "PLUGIN_LOCATION_REGISTRY",
	}
	PluginLocation_value = map[string]int32{
		"PLUGIN_LOCATION_UNSPECIFIED": 0,
		"PLUGIN_LOCATION_SERVER":      1,
		"PLUGIN_LOCATION_STORAGE":     2,
		"PLUGIN_LOCATION_REGISTRY":    3,
	}
)

func (x PluginLocation) Enum() *PluginLocation {
	p := new(PluginLocation)
	*p = x
	return p
}

func (x PluginLocation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginLocation) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_agent_proto_enumTypes[2].Descriptor()
}

func (PluginLocation) Type() protoreflect.EnumType {
	return &file_agent_v1_agent_proto_enumTypes[2]
}

func (x PluginLocation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginLocation.Descriptor instead.
func (PluginLocation) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

// 心跳请求
type HeartbeatRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgentId           string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                                                            // Agent唯一标识
	Status            AgentStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=agent.v1.AgentStatus" json:"status,omitempty"`                                                  // Agent当前状态
	RunningJobsCount  int32                  `protobuf:"varint,3,opt,name=running_jobs_count,json=runningJobsCount,proto3" json:"running_jobs_count,omitempty"`                              // 正在执行的任务数
	MaxConcurrentJobs int32                  `protobuf:"varint,4,opt,name=max_concurrent_jobs,json=maxConcurrentJobs,proto3" json:"max_concurrent_jobs,omitempty"`                           // 最大并发任务数
	Metrics           map[string]string      `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Agent指标（CPU、内存等）
	Labels            map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`   // Agent标签（可动态更新）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (x *HeartbeatRequest) GetRunningJobsCount() int32 {
	if x != nil {
		return x.RunningJobsCount
	}
	return 0
}

func (x *HeartbeatRequest) GetMaxConcurrentJobs() int32 {
	if x != nil {
		return x.MaxConcurrentJobs
	}
	return 0
}

func (x *HeartbeatRequest) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *HeartbeatRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// 心跳响应
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 服务器时间戳（用于时间同步）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HeartbeatResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Agent注册请求
type RegisterRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgentId           string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                                                          // Agent唯一标识（可选，不提供则由Server生成）
	Hostname          string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`                                                                       // 主机名
	Ip                string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`                                                                                   // IP地址
	Os                string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`                                                                                   // 操作系统
	Arch              string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`                                                                               // 架构（amd64、arm64等）
	Version           string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`                                                                         // Agent版本
	MaxConcurrentJobs int32                  `protobuf:"varint,7,opt,name=max_concurrent_jobs,json=maxConcurrentJobs,proto3" json:"max_concurrent_jobs,omitempty"`                         // 最大并发任务数
	Labels            map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 自定义标签
	InstalledPlugins  []string               `protobuf:"bytes,9,rep,name=installed_plugins,json=installedPlugins,proto3" json:"installed_plugins,omitempty"`                               // Agent已安装的插件列表
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetMaxConcurrentJobs() int32 {
	if x != nil {
		return x.MaxConcurrentJobs
	}
	return 0
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterRequest) GetInstalledPlugins() []string {
	if x != nil {
		return x.InstalledPlugins
	}
	return nil
}

// Agent注册响应
type RegisterResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AgentId           string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                                // Server分配或确认的Agent ID
	HeartbeatInterval int64                  `protobuf:"varint,4,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"` // 心跳间隔（秒）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatInterval() int64 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

// Agent注销请求
type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // 注销原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UnregisterRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Agent注销响应
type UnregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResponse) Reset() {
	*x = UnregisterResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResponse) ProtoMessage() {}

func (x *UnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResponse.ProtoReflect.Descriptor instead.
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *UnregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取任务请求
type FetchTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	MaxJobs       int32                  `protobuf:"varint,2,opt,name=max_jobs,json=maxJobs,proto3" json:"max_jobs,omitempty"`                                                         // 最多获取的任务数
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Agent标签（用于任务匹配）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchTaskRequest) Reset() {
	*x = FetchTaskRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchTaskRequest) ProtoMessage() {}

func (x *FetchTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchTaskRequest.ProtoReflect.Descriptor instead.
func (*FetchTaskRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *FetchTaskRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FetchTaskRequest) GetMaxJobs() int32 {
	if x != nil {
		return x.MaxJobs
	}
	return 0
}

func (x *FetchTaskRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// 获取任务响应
type FetchTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Tasks         []*Task                `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"` // 待执行的任务列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchTaskResponse) Reset() {
	*x = FetchTaskResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchTaskResponse) ProtoMessage() {}

func (x *FetchTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchTaskResponse.ProtoReflect.Descriptor instead.
func (*FetchTaskResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *FetchTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FetchTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FetchTaskResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// 任务定义
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                                                                   // 任务ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                  // 任务名称
	PipelineId    string                 `protobuf:"bytes,3,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`                                                    // 所属流水线ID
	Stage         int32                  `protobuf:"varint,4,opt,name=stage,proto3" json:"stage,omitempty"`                                                                               // 阶段序号
	Commands      []string               `protobuf:"bytes,5,rep,name=commands,proto3" json:"commands,omitempty"`                                                                          // 执行命令列表
	Env           map[string]string      `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`          // 环境变量
	Workspace     string                 `protobuf:"bytes,7,opt,name=workspace,proto3" json:"workspace,omitempty"`                                                                        // 工作目录
	Timeout       int32                  `protobuf:"varint,8,opt,name=timeout,proto3" json:"timeout,omitempty"`                                                                           // 超时时间（秒）
	Image         string                 `protobuf:"bytes,9,opt,name=image,proto3" json:"image,omitempty"`                                                                                // Docker镜像（如果需要容器执行）
	Secrets       map[string]string      `protobuf:"bytes,10,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 密钥信息
	Artifacts     []*Artifact            `protobuf:"bytes,11,rep,name=artifacts,proto3" json:"artifacts,omitempty"`                                                                       // 产物配置
	LabelSelector *LabelSelector         `protobuf:"bytes,12,opt,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty"`                                          // 标签选择器（用于匹配Agent）
	Plugins       []*PluginInfo          `protobuf:"bytes,13,rep,name=plugins,proto3" json:"plugins,omitempty"`                                                                           // 任务所需插件列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *Task) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *Task) GetStage() int32 {
	if x != nil {
		return x.Stage
	}
	return 0
}

func (x *Task) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *Task) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Task) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *Task) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *Task) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Task) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *Task) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *Task) GetLabelSelector() *LabelSelector {
	if x != nil {
		return x.LabelSelector
	}
	return nil
}

func (x *Task) GetPlugins() []*PluginInfo {
	if x != nil {
		return x.Plugins
	}
	return nil
}

// 产物定义
type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // 产物名称
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`               // 产物路径（支持glob模式）
	Destination   string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"` // 目标存储路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artifact) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Artifact) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

// 上报任务状态请求
type ReportTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        v1.TaskStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=task.v1.TaskStatus" json:"status,omitempty"`                                                    // 任务状态
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`                                                        // 退出码
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                                             // 错误信息
	StartTime     int64                  `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                                                     // 开始时间（Unix时间戳）
	EndTime       int64                  `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                                                           // 结束时间（Unix时间戳）
	Metrics       map[string]string      `protobuf:"bytes,8,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 任务执行指标
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskStatusRequest) Reset() {
	*x = ReportTaskStatusRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskStatusRequest) ProtoMessage() {}

func (x *ReportTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ReportTaskStatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReportTaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReportTaskStatusRequest) GetStatus() v1.TaskStatus {
	if x != nil {
		return x.Status
	}
	return v1.TaskStatus(0)
}

func (x *ReportTaskStatusRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ReportTaskStatusRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ReportTaskStatusRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ReportTaskStatusRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *ReportTaskStatusRequest) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// 上报任务状态响应
type ReportTaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskStatusResponse) Reset() {
	*x = ReportTaskStatusResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskStatusResponse) ProtoMessage() {}

func (x *ReportTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ReportTaskStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportTaskStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 上报任务日志请求
type ReportTaskLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Logs          []*LogEntry            `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"` // 日志条目
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskLogRequest) Reset() {
	*x = ReportTaskLogRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskLogRequest) ProtoMessage() {}

func (x *ReportTaskLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskLogRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskLogRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ReportTaskLogRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReportTaskLogRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReportTaskLogRequest) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

// 日志条目
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                     // 时间戳
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`                              // 日志级别（info、warn、error）
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                          // 日志内容
	LineNumber    int32                  `protobuf:"varint,4,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"` // 行号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *LogEntry) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

// 上报任务日志响应
type ReportTaskLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskLogResponse) Reset() {
	*x = ReportTaskLogResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskLogResponse) ProtoMessage() {}

func (x *ReportTaskLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskLogResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskLogResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ReportTaskLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportTaskLogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 取消任务请求
type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // 取消原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *CancelTaskRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CancelTaskRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelTaskRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 取消任务响应
type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *CancelTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 更新Agent标签请求
type UpdateLabelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 要更新的标签（完全替换）
	Merge         bool                   `protobuf:"varint,3,opt,name=merge,proto3" json:"merge,omitempty"`                                                                            // 是否合并模式（true=合并，false=替换）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLabelsRequest) Reset() {
	*x = UpdateLabelsRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLabelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLabelsRequest) ProtoMessage() {}

func (x *UpdateLabelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLabelsRequest.ProtoReflect.Descriptor instead.
func (*UpdateLabelsRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateLabelsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UpdateLabelsRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *UpdateLabelsRequest) GetMerge() bool {
	if x != nil {
		return x.Merge
	}
	return false
}

// 更新Agent标签响应
type UpdateLabelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 更新后的标签
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLabelsResponse) Reset() {
	*x = UpdateLabelsResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLabelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLabelsResponse) ProtoMessage() {}

func (x *UpdateLabelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLabelsResponse.ProtoReflect.Descriptor instead.
func (*UpdateLabelsResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateLabelsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateLabelsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateLabelsResponse) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// 标签选择器 - 用于任务匹配Agent
type LabelSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 匹配所有指定的标签（AND逻辑）
	MatchLabels map[string]string `protobuf:"bytes,1,rep,name=match_labels,json=matchLabels,proto3" json:"match_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 标签表达式（支持更复杂的匹配规则）
	MatchExpressions []*LabelSelectorRequirement `protobuf:"bytes,2,rep,name=match_expressions,json=matchExpressions,proto3" json:"match_expressions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LabelSelector) Reset() {
	*x = LabelSelector{}
	mi := &file_agent_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelSelector) ProtoMessage() {}

func (x *LabelSelector) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelSelector.ProtoReflect.Descriptor instead.
func (*LabelSelector) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *LabelSelector) GetMatchLabels() map[string]string {
	if x != nil {
		return x.MatchLabels
	}
	return nil
}

func (x *LabelSelector) GetMatchExpressions() []*LabelSelectorRequirement {
	if x != nil {
		return x.MatchExpressions
	}
	return nil
}

// 标签选择器要求
type LabelSelectorRequirement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                                        // 标签key
	Operator      LabelOperator          `protobuf:"varint,2,opt,name=operator,proto3,enum=agent.v1.LabelOperator" json:"operator,omitempty"` // 操作符
	Values        []string               `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`                                  // 值列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelSelectorRequirement) Reset() {
	*x = LabelSelectorRequirement{}
	mi := &file_agent_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelSelectorRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelSelectorRequirement) ProtoMessage() {}

func (x *LabelSelectorRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelSelectorRequirement.ProtoReflect.Descriptor instead.
func (*LabelSelectorRequirement) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *LabelSelectorRequirement) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LabelSelectorRequirement) GetOperator() LabelOperator {
	if x != nil {
		return x.Operator
	}
	return LabelOperator_LABEL_OPERATOR_UNSPECIFIED
}

func (x *LabelSelectorRequirement) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// 插件信息
type PluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`               // 插件ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                       // 插件名称
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                                 // 版本号
	Checksum      string                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`                               // SHA256校验和
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`                                      // 文件大小（字节）
	DownloadUrl   string                 `protobuf:"bytes,6,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`      // 下载地址（可选，用于CDN分发）
	Location      PluginLocation         `protobuf:"varint,7,opt,name=location,proto3,enum=agent.v1.PluginLocation" json:"location,omitempty"` // 插件位置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_agent_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{21}
}

func (x *PluginInfo) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *PluginInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PluginInfo) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *PluginInfo) GetLocation() PluginLocation {
	if x != nil {
		return x.Location
	}
	return PluginLocation_PLUGIN_LOCATION_UNSPECIFIED
}

// 下载插件请求
type DownloadPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`    // Agent ID
	PluginId      string                 `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"` // 插件ID
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                   // 版本号（可选，不指定则下载最新版本）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadPluginRequest) Reset() {
	*x = DownloadPluginRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadPluginRequest) ProtoMessage() {}

func (x *DownloadPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadPluginRequest.ProtoReflect.Descriptor instead.
func (*DownloadPluginRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{22}
}

func (x *DownloadPluginRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DownloadPluginRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *DownloadPluginRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// 下载插件响应
type DownloadPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                        // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                         // 消息
	PluginData    []byte                 `protobuf:"bytes,3,opt,name=plugin_data,json=pluginData,proto3" json:"plugin_data,omitempty"` // 插件二进制数据
	Checksum      string                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`                       // SHA256校验和
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`                              // 文件大小
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`                         // 实际版本号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadPluginResponse) Reset() {
	*x = DownloadPluginResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadPluginResponse) ProtoMessage() {}

func (x *DownloadPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadPluginResponse.ProtoReflect.Descriptor instead.
func (*DownloadPluginResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{23}
}

func (x *DownloadPluginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DownloadPluginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DownloadPluginResponse) GetPluginData() []byte {
	if x != nil {
		return x.PluginData
	}
	return nil
}

func (x *DownloadPluginResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *DownloadPluginResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DownloadPluginResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// 列出可用插件请求
type ListAvailablePluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`          // Agent ID
	PluginType    string                 `protobuf:"bytes,2,opt,name=plugin_type,json=pluginType,proto3" json:"plugin_type,omitempty"` // 可选：按类型过滤（notify/ci/cd/security等）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailablePluginsRequest) Reset() {
	*x = ListAvailablePluginsRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailablePluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailablePluginsRequest) ProtoMessage() {}

func (x *ListAvailablePluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailablePluginsRequest.ProtoReflect.Descriptor instead.
func (*ListAvailablePluginsRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{24}
}

func (x *ListAvailablePluginsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListAvailablePluginsRequest) GetPluginType() string {
	if x != nil {
		return x.PluginType
	}
	return ""
}

// 列出可用插件响应
type ListAvailablePluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Plugins       []*PluginInfo          `protobuf:"bytes,3,rep,name=plugins,proto3" json:"plugins,omitempty"` // 可用插件列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailablePluginsResponse) Reset() {
	*x = ListAvailablePluginsResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailablePluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailablePluginsResponse) ProtoMessage() {}

func (x *ListAvailablePluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailablePluginsResponse.ProtoReflect.Descriptor instead.
func (*ListAvailablePluginsResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{25}
}

func (x *ListAvailablePluginsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListAvailablePluginsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListAvailablePluginsResponse) GetPlugins() []*PluginInfo {
	if x != nil {
		return x.Plugins
	}
	return nil
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\bagent.v1\x1a\x12task/v1/task.proto\"\xb4\x03\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.agent.v1.AgentStatusR\x06status\x12,\n" +
	"\x12running_jobs_count\x18\x03 \x01(\x05R\x10runningJobsCount\x12.\n" +
	"\x13max_concurrent_jobs\x18\x04 \x01(\x05R\x11maxConcurrentJobs\x12A\n" +
	"\ametrics\x18\x05 \x03(\v2'.agent.v1.HeartbeatRequest.MetricsEntryR\ametrics\x12>\n" +
	"\x06labels\x18\x06 \x03(\v2&.agent.v1.HeartbeatRequest.LabelsEntryR\x06labels\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\xed\x02\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12.\n" +
	"\x13max_concurrent_jobs\x18\a \x01(\x05R\x11maxConcurrentJobs\x12=\n" +
	"\x06labels\x18\b \x03(\v2%.agent.v1.RegisterRequest.LabelsEntryR\x06labels\x12+\n" +
	"\x11installed_plugins\x18\t \x03(\tR\x10installedPlugins\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12-\n" +
	"\x12heartbeat_interval\x18\x04 \x01(\x03R\x11heartbeatInterval\"F\n" +
	"\x11UnregisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"H\n" +
	"\x12UnregisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc3\x01\n" +
	"\x10FetchTaskRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x19\n" +
	"\bmax_jobs\x18\x02 \x01(\x05R\amaxJobs\x12>\n" +
	"\x06labels\x18\x03 \x03(\v2&.agent.v1.FetchTaskRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\x11FetchTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x05tasks\x18\x03 \x03(\v2\x0e.agent.v1.TaskR\x05tasks\"\xca\x04\n" +
	"\x04Task\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vpipeline_id\x18\x03 \x01(\tR\n" +
	"pipelineId\x12\x14\n" +
	"\x05stage\x18\x04 \x01(\x05R\x05stage\x12\x1a\n" +
	"\bcommands\x18\x05 \x03(\tR\bcommands\x12)\n" +
	"\x03env\x18\x06 \x03(\v2\x17.agent.v1.Task.EnvEntryR\x03env\x12\x1c\n" +
	"\tworkspace\x18\a \x01(\tR\tworkspace\x12\x18\n" +
	"\atimeout\x18\b \x01(\x05R\atimeout\x12\x14\n" +
	"\x05image\x18\t \x01(\tR\x05image\x125\n" +
	"\asecrets\x18\n" +
	" \x03(\v2\x1b.agent.v1.Task.SecretsEntryR\asecrets\x120\n" +
	"\tartifacts\x18\v \x03(\v2\x12.agent.v1.ArtifactR\tartifacts\x12>\n" +
	"\x0elabel_selector\x18\f \x01(\v2\x17.agent.v1.LabelSelectorR\rlabelSelector\x12.\n" +
	"\aplugins\x18\r \x03(\v2\x14.agent.v1.PluginInfoR\aplugins\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\bArtifact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\"\xfc\x02\n" +
	"\x17ReportTaskStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.task.v1.TaskStatusR\x06status\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\x03R\aendTime\x12H\n" +
	"\ametrics\x18\b \x03(\v2..agent.v1.ReportTaskStatusRequest.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x18ReportTaskStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"r\n" +
	"\x14ReportTaskLogRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12&\n" +
	"\x04logs\x18\x03 \x03(\v2\x12.agent.v1.LogEntryR\x04logs\"y\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1f\n" +
	"\vline_number\x18\x04 \x01(\x05R\n" +
	"lineNumber\"K\n" +
	"\x15ReportTaskLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\x11CancelTaskRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"H\n" +
	"\x12CancelTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc4\x01\n" +
	"\x13UpdateLabelsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12A\n" +
	"\x06labels\x18\x02 \x03(\v2).agent.v1.UpdateLabelsRequest.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05merge\x18\x03 \x01(\bR\x05merge\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x01\n" +
	"\x14UpdateLabelsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12B\n" +
	"\x06labels\x18\x03 \x03(\v2*.agent.v1.UpdateLabelsResponse.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xed\x01\n" +
	"\rLabelSelector\x12K\n" +
	"\fmatch_labels\x18\x01 \x03(\v2(.agent.v1.LabelSelector.MatchLabelsEntryR\vmatchLabels\x12O\n" +
	"\x11match_expressions\x18\x02 \x03(\v2\".agent.v1.LabelSelectorRequirementR\x10matchExpressions\x1a>\n" +
	"\x10MatchLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\x18LabelSelectorRequirement\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\boperator\x18\x02 \x01(\x0e2\x17.agent.v1.LabelOperatorR\boperator\x12\x16\n" +
	"\x06values\x18\x03 \x03(\tR\x06values\"\xe0\x01\n" +
	"\n" +
	"PluginInfo\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12!\n" +
	"\fdownload_url\x18\x06 \x01(\tR\vdownloadUrl\x124\n" +
	"\blocation\x18\a \x01(\x0e2\x18.agent.v1.PluginLocationR\blocation\"i\n" +
	"\x15DownloadPluginRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xb7\x01\n" +
	"\x16DownloadPluginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vplugin_data\x18\x03 \x01(\fR\n" +
	"pluginData\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\"Y\n" +
	"\x1bListAvailablePluginsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vplugin_type\x18\x02 \x01(\tR\n" +
	"pluginType\"\x82\x01\n" +
	"\x1cListAvailablePluginsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\aplugins\x18\x03 \x03(\v2\x14.agent.v1.PluginInfoR\aplugins*\x8c\x01\n" +
	"\vAgentStatus\x12\x1c\n" +
	"\x18AGENT_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13AGENT_STATUS_ONLINE\x10\x01\x12\x18\n" +
	"\x14AGENT_STATUS_OFFLINE\x10\x02\x12\x15\n" +
	"\x11AGENT_STATUS_BUSY\x10\x03\x12\x15\n" +
	"\x11AGENT_STATUS_IDLE\x10\x04*\xc9\x01\n" +
	"\rLabelOperator\x12\x1e\n" +
	"\x1aLABEL_OPERATOR_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LABEL_OPERATOR_IN\x10\x01\x12\x19\n" +
	"\x15LABEL_OPERATOR_NOT_IN\x10\x02\x12\x19\n" +
	"\x15LABEL_OPERATOR_EXISTS\x10\x03\x12\x1d\n" +
	"\x19LABEL_OPERATOR_NOT_EXISTS\x10\x04\x12\x15\n" +
	"\x11LABEL_OPERATOR_GT\x10\x05\x12\x15\n" +
	"\x11LABEL_OPERATOR_LT\x10\x06*\x88\x01\n" +
	"\x0ePluginLocation\x12\x1f\n" +
	"\x1bPLUGIN_LOCATION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PLUGIN_LOCATION_SERVER\x10\x01\x12\x1b\n" +
	"\x17PLUGIN_LOCATION_STORAGE\x10\x02\x12\x1c\n" +
	"\x18PLUGIN_LOCATION_REGISTRY\x10\x032\xbb\x06\n" +
	"\fAgentService\x12F\n" +
	"\tHeartbeat\x12\x1a.agent.v1.HeartbeatRequest\x1a\x1b.agent.v1.HeartbeatResponse\"\x00\x12C\n" +
	"\bRegister\x12\x19.agent.v1.RegisterRequest\x1a\x1a.agent.v1.RegisterResponse\"\x00\x12I\n" +
	"\n" +
	"Unregister\x12\x1b.agent.v1.UnregisterRequest\x1a\x1c.agent.v1.UnregisterResponse\"\x00\x12F\n" +
	"\tFetchTask\x12\x1a.agent.v1.FetchTaskRequest\x1a\x1b.agent.v1.FetchTaskResponse\"\x00\x12[\n" +
	"\x10ReportTaskStatus\x12!.agent.v1.ReportTaskStatusRequest\x1a\".agent.v1.ReportTaskStatusResponse\"\x00\x12R\n" +
	"\rReportTaskLog\x12\x1e.agent.v1.ReportTaskLogRequest\x1a\x1f.agent.v1.ReportTaskLogResponse\"\x00\x12I\n" +
	"\n" +
	"CancelTask\x12\x1b.agent.v1.CancelTaskRequest\x1a\x1c.agent.v1.CancelTaskResponse\"\x00\x12O\n" +
	"\fUpdateLabels\x12\x1d.agent.v1.UpdateLabelsRequest\x1a\x1e.agent.v1.UpdateLabelsResponse\"\x00\x12U\n" +
	"\x0eDownloadPlugin\x12\x1f.agent.v1.DownloadPluginRequest\x1a .agent.v1.DownloadPluginResponse\"\x00\x12g\n" +
	"\x14ListAvailablePlugins\x12%.agent.v1.ListAvailablePluginsRequest\x1a&.agent.v1.ListAvailablePluginsResponse\"\x00B3Z1github.com/observabil/arcade/api/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_agent_v1_agent_proto_goTypes = []any{
	(AgentStatus)(0),                     // 0: agent.v1.AgentStatus
	(LabelOperator)(0),                   // 1: agent.v1.LabelOperator
	(PluginLocation)(0),                  // 2: agent.v1.PluginLocation
	(*HeartbeatRequest)(nil),             // 3: agent.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),            // 4: agent.v1.HeartbeatResponse
	(*RegisterRequest)(nil),              // 5: agent.v1.RegisterRequest
	(*RegisterResponse)(nil),             // 6: agent.v1.RegisterResponse
	(*UnregisterRequest)(nil),            // 7: agent.v1.UnregisterRequest
	(*UnregisterResponse)(nil),           // 8: agent.v1.UnregisterResponse
	(*FetchTaskRequest)(nil),             // 9: agent.v1.FetchTaskRequest
	(*FetchTaskResponse)(nil),            // 10: agent.v1.FetchTaskResponse
	(*Task)(nil),                         // 11: agent.v1.Task
	(*Artifact)(nil),                     // 12: agent.v1.Artifact
	(*ReportTaskStatusRequest)(nil),      // 13: agent.v1.ReportTaskStatusRequest
	(*ReportTaskStatusResponse)(nil),     // 14: agent.v1.ReportTaskStatusResponse
	(*ReportTaskLogRequest)(nil),         // 15: agent.v1.ReportTaskLogRequest
	(*LogEntry)(nil),                     // 16: agent.v1.LogEntry
	(*ReportTaskLogResponse)(nil),        // 17: agent.v1.ReportTaskLogResponse
	(*CancelTaskRequest)(nil),            // 18: agent.v1.CancelTaskRequest
	(*CancelTaskResponse)(nil),           // 19: agent.v1.CancelTaskResponse
	(*UpdateLabelsRequest)(nil),          // 20: agent.v1.UpdateLabelsRequest
	(*UpdateLabelsResponse)(nil),         // 21: agent.v1.UpdateLabelsResponse
	(*LabelSelector)(nil),                // 22: agent.v1.LabelSelector
	(*LabelSelectorRequirement)(nil),     // 23: agent.v1.LabelSelectorRequirement
	(*PluginInfo)(nil),                   // 24: agent.v1.PluginInfo
	(*DownloadPluginRequest)(nil),        // 25: agent.v1.DownloadPluginRequest
	(*DownloadPluginResponse)(nil),       // 26: agent.v1.DownloadPluginResponse
	(*ListAvailablePluginsRequest)(nil),  // 27: agent.v1.ListAvailablePluginsRequest
	(*ListAvailablePluginsResponse)(nil), // 28: agent.v1.ListAvailablePluginsResponse
	nil,                                  // 29: agent.v1.HeartbeatRequest.MetricsEntry
	nil,                                  // 30: agent.v1.HeartbeatRequest.LabelsEntry
	nil,                                  // 31: agent.v1.RegisterRequest.LabelsEntry
	nil,                                  // 32: agent.v1.FetchTaskRequest.LabelsEntry
	nil,                                  // 33: agent.v1.Task.EnvEntry
	nil,                                  // 34: agent.v1.Task.SecretsEntry
	nil,                                  // 35: agent.v1.ReportTaskStatusRequest.MetricsEntry
	nil,                                  // 36: agent.v1.UpdateLabelsRequest.LabelsEntry
	nil,                                  // 37: agent.v1.UpdateLabelsResponse.LabelsEntry
	nil,                                  // 38: agent.v1.LabelSelector.MatchLabelsEntry
	(v1.TaskStatus)(0),                   // 39: task.v1.TaskStatus
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	0,  // 0: agent.v1.HeartbeatRequest.status:type_name -> agent.v1.AgentStatus
	29, // 1: agent.v1.HeartbeatRequest.metrics:type_name -> agent.v1.HeartbeatRequest.MetricsEntry
	30, // 2: agent.v1.HeartbeatRequest.labels:type_name -> agent.v1.HeartbeatRequest.LabelsEntry
	31, // 3: agent.v1.RegisterRequest.labels:type_name -> agent.v1.RegisterRequest.LabelsEntry
	32, // 4: agent.v1.FetchTaskRequest.labels:type_name -> agent.v1.FetchTaskRequest.LabelsEntry
	11, // 5: agent.v1.FetchTaskResponse.tasks:type_name -> agent.v1.Task
	33, // 6: agent.v1.Task.env:type_name -> agent.v1.Task.EnvEntry
	34, // 7: agent.v1.Task.secrets:type_name -> agent.v1.Task.SecretsEntry
	12, // 8: agent.v1.Task.artifacts:type_name -> agent.v1.Artifact
	22, // 9: agent.v1.Task.label_selector:type_name -> agent.v1.LabelSelector
	24, // 10: agent.v1.Task.plugins:type_name -> agent.v1.PluginInfo
	39, // 11: agent.v1.ReportTaskStatusRequest.status:type_name -> task.v1.TaskStatus
	35, // 12: agent.v1.ReportTaskStatusRequest.metrics:type_name -> agent.v1.ReportTaskStatusRequest.MetricsEntry
	16, // 13: agent.v1.ReportTaskLogRequest.logs:type_name -> agent.v1.LogEntry
	36, // 14: agent.v1.UpdateLabelsRequest.labels:type_name -> agent.v1.UpdateLabelsRequest.LabelsEntry
	37, // 15: agent.v1.UpdateLabelsResponse.labels:type_name -> agent.v1.UpdateLabelsResponse.LabelsEntry
	38, // 16: agent.v1.LabelSelector.match_labels:type_name -> agent.v1.LabelSelector.MatchLabelsEntry
	23, // 17: agent.v1.LabelSelector.match_expressions:type_name -> agent.v1.LabelSelectorRequirement
	1,  // 18: agent.v1.LabelSelectorRequirement.operator:type_name -> agent.v1.LabelOperator
	2,  // 19: agent.v1.PluginInfo.location:type_name -> agent.v1.PluginLocation
	24, // 20: agent.v1.ListAvailablePluginsResponse.plugins:type_name -> agent.v1.PluginInfo
	3,  // 21: agent.v1.AgentService.Heartbeat:input_type -> agent.v1.HeartbeatRequest
	5,  // 22: agent.v1.AgentService.Register:input_type -> agent.v1.RegisterRequest
	7,  // 23: agent.v1.AgentService.Unregister:input_type -> agent.v1.UnregisterRequest
	9,  // 24: agent.v1.AgentService.FetchTask:input_type -> agent.v1.FetchTaskRequest
	13, // 25: agent.v1.AgentService.ReportTaskStatus:input_type -> agent.v1.ReportTaskStatusRequest
	15, // 26: agent.v1.AgentService.ReportTaskLog:input_type -> agent.v1.ReportTaskLogRequest
	18, // 27: agent.v1.AgentService.CancelTask:input_type -> agent.v1.CancelTaskRequest
	20, // 28: agent.v1.AgentService.UpdateLabels:input_type -> agent.v1.UpdateLabelsRequest
	25, // 29: agent.v1.AgentService.DownloadPlugin:input_type -> agent.v1.DownloadPluginRequest
	27, // 30: agent.v1.AgentService.ListAvailablePlugins:input_type -> agent.v1.ListAvailablePluginsRequest
	4,  // 31: agent.v1.AgentService.Heartbeat:output_type -> agent.v1.HeartbeatResponse
	6,  // 32: agent.v1.AgentService.Register:output_type -> agent.v1.RegisterResponse
	8,  // 33: agent.v1.AgentService.Unregister:output_type -> agent.v1.UnregisterResponse
	10, // 34: agent.v1.AgentService.FetchTask:output_type -> agent.v1.FetchTaskResponse
	14, // 35: agent.v1.AgentService.ReportTaskStatus:output_type -> agent.v1.ReportTaskStatusResponse
	17, // 36: agent.v1.AgentService.ReportTaskLog:output_type -> agent.v1.ReportTaskLogResponse
	19, // 37: agent.v1.AgentService.CancelTask:output_type -> agent.v1.CancelTaskResponse
	21, // 38: agent.v1.AgentService.UpdateLabels:output_type -> agent.v1.UpdateLabelsResponse
	26, // 39: agent.v1.AgentService.DownloadPlugin:output_type -> agent.v1.DownloadPluginResponse
	28, // 40: agent.v1.AgentService.ListAvailablePlugins:output_type -> agent.v1.ListAvailablePluginsResponse
	31, // [31:41] is the sub-list for method output_type
	21, // [21:31] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
